[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "instagram-connector"
version = "0.1.0"
description = "A connector for Instagram to fetch posts such as images, comments and texts."
requires-python = ">=3.9"
dependencies = [
    "requests>=2.25.1",
    "python-dotenv>=1.2.0",
    "pymongo",
    "pydantic-settings"
]

[tool.setuptools.packages.find]
where = ["src"]
